### ISSUE TITLE
Recursive usage of "ConversationScreen" in the state-hoisting snippet is confusing

### ISSUE THREAD

**Issue by Sal7one** [android/snippets#121]
![image](https://github.com/android/snippets/assets/20628286/de6dccbc-b87f-45ba-85be-67a02459748e)

https://github.com/android/snippets/blame/7322f58994e9ade5ffee8e49f956e4a97339f384/compose/snippets/src/main/java/com/example/compose/snippets/state/StateHoistingSnippets.kt#L177-L198

Edit: I get why it's made this way, I just don't think it's ideal for a snippet in the docs

**Comment by Gifts1998** [comment]
> ![ภาพ](https://user-images.githubuserhttps://github.com/android/snippets/issues/121#issue-1789168836content.com/20628286/251106468-de6dccbc-b87f-45ba-85be-67a02459748e.png)
> 
>  #https://github.com/android/snippets/blame/7322f58994e9ade5ffee8e49f956e4a97339f384/compose/snippets/src/main/java/com/example/compose/snippets/state/StateHoistingSnippets.kt#L177-L198
> 
> แก้ไข: ฉันเข้าใจว่าทำไมมันถึงทำแบบนี้ ฉันไม่คิดว่ามันเหมาะสำหรับตัวอย่างในเอกสาร

**Comment by Gifts1998** [comment]
https://github.com/android/snippets/issues/121#issue-1789168836

**Comment by Gifts1998** [comment]
https://github.com/android/snippets/blame/7322f58994e9ade5ffee8e49f956e4a97339f384/compose/snippets/src/main/java/com/example/compose/snippets/state/StateHoistingSnippets.kt#L177-L198
