### ISSUE TITLE
How to Implement a Timer Scheme with GlanceAppWidget

### ISSUE THREAD

**Issue by wangzhankai** [android/snippets#172]
How to Implement a Timer Scheme with GlanceAppWidget

**Comment by secondsun** [comment]
Hi!

This repository is for hosting code snippets found on [developer.android.com](https://developer.android.com). If you have a feature or documentation request for Glance, please create a bug using our [public issue tracker](https://b.corp.google.com/issues/new?component=1097239&template=1611667).

If you are asking for support, the [glance-appwidget](https://stackoverflow.com/questions/tagged/glance-appwidget) tag is monitored on Stackoverflow, as well as the glance channels in the kotlinlang and Android Study Group Slacks.
