### ISSUE TITLE
detectTapGestures and detectDragGestures not working even add two PointerInput

### ISSUE THREAD

**Issue by ranjithbobby89** [android/snippets#243]
https://github.com/android/snippets/blob/7925f9d19a3a4bca15ef68892ea4938da6157f85/compose/snippets/src/main/java/com/example/compose/snippets/touchinput/pointerinput/UnderstandGesturesSnippets.kt#L151-L166

Only detectDragGestures was works

**Comment by JolandaVerhoef** [comment]
Ran this on a Pixel 7 SDK 34 emulator, when tapping I see the "Tap!" text, when dragging I see "Dragging". Works as expected, so I'll close this issue. Feel free to re-open with more specific steps to reproduce.
