### ISSUE TITLE
addOnUserLeaveHintListener

### ISSUE THREAD

**Issue by yayahassani** [android/snippets#246]
In this [snippet](https://github.com/android/snippets/blob/bf832068dcded0fdb533434a0847bac69b44b8a7/compose/snippets/src/main/java/com/example/compose/snippets/pictureinpicture/PictureInPictureSnippets.kt#L35-L55) and the documentation mentioned to use the `addOnUserLeaveHintListener` to register a listener for user leave action of the activity but I have not found such a method. I am using the latest version of `androidx.activity:activity` which is `1.8.2`.

**Comment by IanGClifton** [comment]
It looks like these are in [1.9.0-alpha01](https://developer.android.com/jetpack/androidx/releases/activity#1.9.0-alpha01) and newer. I'm not sure what the release schedule for that artifact is, but it looks like there's currently a beta, so hopefully a stable release is coming soon.

For reference, this is defined in the OnUserLeaveHintProvider [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/app/OnUserLeaveHintProvider.kt;l=33?q=addOnUserLeaveHintListener&ss=androidx%2Fplatform%2Fframeworks%2Fsupport) and implemented in ComponentActivity [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:activity/activity/src/main/java/androidx/activity/ComponentActivity.kt;l=1041?q=addOnUserLeaveHintListener&ss=androidx%2Fplatform%2Fframeworks%2Fsupport).
