### ISSUE TITLE
https://terabox.com/s/1IxRTWAM8Z70lL1KP-mPfHQ

### ISSUE THREAD

**Issue by Castillon35** [android/snippets#406]
Hi, I am sharing "Welcome_thumbnail_tablet.png" with you through TeraBox. Please click or copy the link to view it in TeraBox~ 
  https://terabox.com/s/1IxRTWAM8Z70lL1KP-mPfHQ 
 extract code: 6d7j

**Comment by mlykotom** [comment]
Could you give more information what is it and why are you sharing this? 
It doesn't look like something that would be contributing to this repository, in fact it looks like a spam.
I'm closing until you give more information.
